CREATE DATABASE IF NOT EXISTS `felixlogin` DEFAULT CHARACTER SET UTF8_GENERAL_CI;
USE `felixlogin`;

CREATE TABLE IF NOT EXISTS `accounts`(
	`id` INT(11) NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT 2 DEFAULT CHARSET UTF8;